services:
  - type: web
    name: ai-image-detector
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: PYTHON_PATH
        value: /usr/bin/python3
    buildFilter:
      paths:
        - server.js
        - predict.py
        - public/*
    autoDeploy: true
